[general]
log_file = "host_test.log"
log_debug = true

[server]
listen_players = ["0.0.0.0:13370"]
cert = ["cert/host00.cert.der", "cert/hosts.ca.cert.der", "cert/root.ca.cert.der"]
key = "cert/host00.key.der"
ip_control = "Denylist"
ip_list = []
player_ca = "cert/apps.ca.cert.der"
allow_players_unexpected = true
allow_players_nocert = true
allow_players_anyip = true
allow_anysession = true
allow_spectators = true

[rpc]
enable = true
listen = ["127.0.0.1:13371"]
cert = ["cert/host00rpc.cert.der", "cert/hosts.ca.cert.der", "cert/root.ca.cert.der"]
key = "cert/host00rpc.key.der"
require_client_cert = false
client_ca = "cert/hostrpc.cert.der"
ip_control = "Denylist"
ip_list = []
allow_payloads = ["Minewars", "TomlRules"]
rpc_method_control = "Denylist"
rpc_methods_list = []

[hostauth]
enable = false
server = "127.0.0.1:13372"
cert = ["cert/host00hostauth.cert.der", "cert/hosts.ca.cert.der", "cert/root.ca.cert.der"]
key = "cert/host00hostauth.key.der"
allow_payloads = ["Minewars", "TomlRules"]
rpc_method_control = "Denylist"
rpc_methods_list = []

[sessions]
max_sessions = 4
autosession = "minewars_duel"
autostart = { minewars_largeopenduos = 1, minesweeper4 = 1 }

[sessions.preset.minewars_duel]
mode = "MineWars"
autorestart = true
open_session = false
allow_spectators = true
n_plids = 2
n_subplids = 1
map_mode = "Generate"
map_topology = "Hex"
map_style = "MineWars"
map_size = 24
map_n_cits = 5
map_land_bias = 48

[sessions.preset.minesweeper4]
mode = "Minesweeper"
autorestart = true
open_session = true
n_plids = 4
n_subplids = 1
map_mode = "Generate"
map_topology = "Hex"
map_style = "MineWars"
map_size = 48
map_n_cits = 0
map_land_bias = 48

[sessions.session.minewars_largeopenduos]
mode = "MineWars"
autorestart = true
open_session = true
n_plids = 6
n_subplids = 2
map_mode = "Generate"
map_topology = "Hex"
map_style = "MineWars"
map_size = 80
map_n_cits = 12
map_land_bias = 48
