[package]
name = "minewars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.iyesengine]
git = "https://github.com/IyesGames/iyesengine"
features = [
    "2d",
    "bevy-ui",
    "audio",
    "tilemap",
]
