[package]
name = "minewars"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

# UNCOMMENT for my machine / local development
[patch."https://github.com/IyesGames/iyes_bevy_extras"]
iyes_bevy_extras = { path = "../../engine/iyes_bevy_extras" }
[patch."https://github.com/IyesGames/iyes_cli"]
iyes_cli = { path = "../../engine/iyes_cli" }
[patch."https://github.com/IyesGames/iyes_ui"]
iyes_ui = { path = "../../engine/iyes_ui" }

# PROPRIETARY BUILDS
[patch."https://github.com/IyesGames/minewars-proprietary-shim"]
mw_app_proprietary = { path = "../minewars-proprietary/lib/mw_app_proprietary" }
mw_host_proprietary = { path = "../minewars-proprietary/lib/mw_host_proprietary" }
mw_auth_proprietary = { path = "../minewars-proprietary/lib/mw_auth_proprietary" }

# [patch.crates-io]
# bevy_ecs_tilemap = { path = "../../../src/bevy_ecs_tilemap"}

[workspace]
resolver = "2"
members = [
    # binaries:
    # (self) # desktop client app
    "mobile", # mobile client app
    "bin/mw_authsrv", # Auth Server
    "bin/mw_hostsrv", # Host Server
    "bin/mw_certgen", # Cert Mgmt CLI
    "bin/mw_datatool", # CLI for mw_dataformat
    "bin/mw_hostrpc", # CLI for controlling Host
    # foundational
    "lib/mw_common", # Common code for everything
    "lib/mw_dataformat", # Dataformat codec
    # protocols
    "lib/mw_proto_auth", # Client <> Auth
    "lib/mw_proto_host", # Client <> Host
    "lib/mw_proto_hostrpc", # HostRPC <> Host
    "lib/mw_proto_hostauth", # Host <> Auth
    # server stuff
    "lib/mw_host", # FOSS part of Host Server
    "lib/mw_auth", # FOSS part of Auth Server
    # client stuff
    "lib/mw_engine", # Bespoke tech for mw_app
    "lib/mw_app", # FOSS part of Game Client sans UI
    "lib/mw_ui_desktop", # Desktop UI of mw_app
    "lib/mw_ui_mobile",  # Mobile UI of mw_app
    # gameplay for different game modes
    "lib/mw_game_minesweeper", # FOSS minesweeper mode
]

# dev: no LTO, some optimization,
# lots of codegen units for parallelism during compilation
[profile.dev]
opt-level = 1
debug = false
lto = false
codegen-units = 16
# release: Enable LTO and limit codegen units for better codegen
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false

[features]
default = ["gfx2d_tilemap", "gfx3d", "buttplug"]
dev = ["mw_engine/dev", "mw_app/dev", "mw_ui_desktop/dev", "mw_ui_mobile/dev"]
release = ["mw_engine/release", "mw_app/release", "mw_ui_desktop/release", "mw_ui_mobile/release"]
proprietary = ["mw_app/proprietary", "dep:mw_app_proprietary"]
gfx2d = ["mw_app/gfx2d"]
gfx2d_tilemap = ["mw_app/gfx2d_tilemap"]
gfx3d = ["mw_app/gfx3d"]
buttplug = ["mw_app/buttplug"]

[dependencies.mw_engine]
path = "lib/mw_engine"

[dependencies.mw_app]
path = "lib/mw_app"

[dependencies.mw_ui_desktop]
path = "lib/mw_ui_desktop"

[dependencies.mw_ui_mobile]
path = "lib/mw_ui_mobile"

[dependencies.mw_app_proprietary]
git = "https://github.com/IyesGames/minewars-proprietary-shim"
optional = true

[dependencies.bevy]
version = "0.13.2"
default-features = false
