[package]
name = "minewars"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

[workspace]
resolver = "2"
members = ["lib/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
proprietary = [
    "mw_proprietary",
]
dev = [
    "iyesengine/dev",
]
release = [
    "iyesengine/release",
]

[dependencies.iyesengine]
git = "https://github.com/IyesGames/iyesengine"
features = [
    "2d",
    "bevy-ui",
    "audio",
    "tilemap",
]

[dependencies.tokio]
version = "1.17.0"
features = [
    "sync",
]

[dependencies]
mw_common = { path = "lib/mw_common" }
mw_dataformat = { path = "lib/mw_dataformat" }
anyhow = "1.0.57"

[dependencies.mw_proprietary]
path = "../minewars-proprietary/client"
optional = true

[package.metadata.android]
apk_label = "MineWars"
assets = "assets"
# res = "assets/android-res"
# icon = "@mipmap/ic_launcher"
build_targets = [
    "aarch64-linux-android",
    # "armv7-linux-androideabi",
    # "x86_64-linux-android",
]
min_sdk_version = 16
target_sdk_version = 29
