[package]
name = "minewars"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

# UNCOMMENT for my machine / local development
[patch."https://github.com/IyesGames/iyes_bevy_extras"]
iyes_bevy_extras = { path = "../../engine/iyes_bevy_extras" }
[patch."https://github.com/IyesGames/iyes_cli"]
iyes_cli = { path = "../../engine/iyes_cli" }
[patch."https://github.com/IyesGames/iyes_ui"]
iyes_ui = { path = "../../engine/iyes_ui" }

[workspace]
resolver = "2"
members = ["proprietary", "lib/*"]

# dev: Enable max optimizations for dependencies, but not for our code
[profile.dev.package."*"]
opt-level = 3
# dev: no LTO, lots of codegen units for parallelism during compilation
[profile.dev]
debug = false
lto = false
codegen-units = 8
# release: Enable LTO and limit codegen units for better codegen
[profile.release]
lto = true
codegen-units = 1
debug = false
strip = true

[features]
dev = ["bevy/filesystem_watcher"]
release = []

[dependencies]
directories = "5.0.1"
enum-iterator = "1.4.1"
fluent_content = "0.0.5"
modular-bitfield = "0.11.2"
serde = "1.0.188"
toml = "0.7.6"
unic-langid = "0.9.1"

[dependencies.mw_common]
path = "lib/mw_common"
features = [ "bevy" ]

[dependencies.mw_proprietary]
path = "proprietary"

[dependencies.iyes_bevy_extras]
git = "https://github.com/IyesGames/iyes_bevy_extras"
features = ["2d"]

[dependencies.iyes_cli]
git = "https://github.com/IyesGames/iyes_cli"

[dependencies.iyes_ui]
git = "https://github.com/IyesGames/iyes_ui"
features = ["iyes_cli"]

[dependencies.tokio]
version = "1.32.0"
features = [
    "parking_lot",
    "rt",
    "sync",
]

[dependencies.bevy]
version = "0.11.2"
# default-features = false
features = [
    "multi-threaded",
    "android_shared_stdcxx",
    "bevy_asset",
    "bevy_scene",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_gizmos",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_gilrs",
    "bevy_winit",
    "tonemapping_luts",
    "png",
    "ktx2",
    "zstd",
    "x11",
    "wayland",
    "bevy_audio",
    "flac",
]

[dependencies.iyes_progress]
version = "0.9.1"
features = []

[dependencies.bevy_asset_loader]
version = "0.17.0"
features = [
    "progress_tracking",
    "standard_dynamic_assets",
]

[dependencies.bevy_common_assets]
version = "0.7.0"
features = [
    "ron",
    "toml",
]

[dependencies.bevy_fluent]
version = "0.7.0"
features = []

[dependencies.bevy_tweening]
version = "0.8.0"

[dependencies.bevy_ecs_tilemap]
version = "0.11.0"

[dependencies.bevy_prototype_lyon]
version = "0.9.0"

