[package]
name = "minewars"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

[workspace]
resolver = "2"
members = ["lib/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
proprietary = [
    "mw_proprietary",
]
dev = [
    "bevy/filesystem_watcher",
]
release = [
]

# dev: Enable max optimizations for dependencies, but not for our code
[profile.dev.package."*"]
opt-level = 3
# dev: no LTO, lots of codegen units for parallelism during compilation
[profile.dev]
lto = false
codegen-units = 8
# release: Enable LTO and limit codegen units for better codegen
[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[package.metadata.android]
apk_label = "MineWars"
assets = "assets"
# res = "assets/android-res"
# icon = "@mipmap/ic_launcher"
build_targets = [
    "aarch64-linux-android",
    # "armv7-linux-androideabi",
    # "x86_64-linux-android",
]
min_sdk_version = 16
target_sdk_version = 29

[dependencies]
mw_common = { path = "lib/mw_common", features = ["bevy"] }
mw_dataformat = { path = "lib/mw_dataformat" }
mw_game_classic = { path = "lib/mw_game_classic" }
anyhow = "1.0.70"
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive", "serde_derive"] }

[dependencies.mw_proprietary]
path = "./proprietary/client"
optional = true

[dependencies.bevy]
version = "0.10.1"
default-features = false
features = [
	"android_shared_stdcxx",
	"tonemapping_luts",
	"bevy_asset",
	"bevy_core_pipeline",
	# "bevy_gilrs",
	"bevy_render",
	"bevy_scene",
	"bevy_sprite",
	"bevy_text",
	"bevy_ui",
	"bevy_winit",
	"ktx2",
	"png",
	"zstd",
	"x11",
	"wayland",
	"accesskit_unix",
	# TODO: let's give bevy audio a try, switch to kira if not good enough
	"bevy_audio",
	"flac",
]

[dependencies.tokio]
version = "1.27.0"
features = [
    "sync",
]

[dependencies.bevy_asset_loader]
version = "0.16.0"
features = [
    "2d",
    "progress_tracking",
    "standard_dynamic_assets",
]

[dependencies.bevy_common_assets]
version = "0.6.0"
features = [
    "ron",
    "toml",
]

[dependencies.bevy_fluent]
version = "0.6.0"
features = []

[dependencies.bevy_mod_ui_texture_atlas_image]
version = "0.4.1"
features = []

[dependencies.bevy_tweening]
version = "0.7.0"
features = []

[dependencies.bevy_ecs_tilemap]
version = "0.10.0"
features = []

[dependencies.iyes_progress]
version = "0.8.0"
features = []

[dependencies.iyes_bevy_extras]
git = "https://github.com/IyesGames/iyes_bevy_extras"

[dependencies.leafwing-input-manager]
version = "0.9.1"
features = []

