[package]
name = "mw_authsrv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
proprietary = ["mw_auth/proprietary", "dep:mw_auth_proprietary"]

[dependencies]
mw_auth = { path = "../../lib/srv/mw_auth" }

[dependencies.mw_auth_proprietary]
git = "https://github.com/IyesGames/minewars-proprietary-shim"
optional = true
