[package]
name = "mw_hostrpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mw_dataformat = { path = "../../lib/mw_dataformat" }
mw_proto_hostrpc = { path = "../../lib/mw_proto_hostrpc" }
anyhow = "1.0.75"
ron = "0.8.1"

[dependencies.mw_common]
path = "../../lib/mw_common"
features = [ "net" ]

[dependencies.serde]
version = "1.0.188"
features = [ "derive" ]

[dependencies.clap]
version = "4.4.3"
features = [ "derive" ]

[dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter"]

[dependencies.tracing]
version = "0.1.37"
features = ["async-await"]
