[package]
name = "mw_hostrpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mw_dataformat = { path = "../../lib/common/mw_dataformat" }
mw_proto_hostrpc = { path = "../../lib/common/mw_proto_hostrpc" }
anyhow = "1.0.86"
ron = "0.8.1"

[dependencies.mw_common]
path = "../../lib/common/mw_common"
features = [ "net" ]

[dependencies.serde]
version = "1.0.204"
features = [ "derive" ]

[dependencies.clap]
version = "4.5.9"
features = [ "derive" ]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]

[dependencies.tracing]
version = "0.1.40"
features = ["async-await"]
