[package]
name = "mw_hostrpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mw_common = { path = "../../lib/mw_common" }
mw_dataformat = { path = "../../lib/mw_dataformat" }
mw_proto_hostrpc = { path = "../../lib/mw_proto_hostrpc" }
anyhow = "1.0.75"
ron = "0.8.1"

[dependencies.serde]
version = "1.0.188"
features = [ "derive" ]

[dependencies.clap]
version = "4.4.3"
features = [ "derive" ]

[dependencies.tokio]
version = "1.32.0"
features = [
    "parking_lot",
    "rt",
    "io-util",
    "fs",
    "net",
    "tracing",
    "macros",
]

[dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter"]

[dependencies.tracing]
version = "0.1.37"
features = ["async-await"]

[dependencies.rustls]
version = "0.20.8" # must be whatever quinn uses
default-features = false
features = []

[dependencies.quinn]
version = "0.9.3"
default-features = false
features = ["runtime-tokio", "tls-rustls"]
