[package]
name = "mw_certgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"

[dependencies.rcgen]
version = "0.12"
default-features = false
features = ["ring", "x509-parser"]

[dependencies.clap]
version = "4.5.9"
features = ["derive"]
