[package]
name = "mw_datatool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"

[dependencies.mw_common]
path = "../../lib/common/mw_common"

[dependencies.mw_dataformat]
path = "../../lib/common/mw_dataformat"

[dependencies.clap]
version = "4.5.9"
features = ["derive"]
