[package]
name = "mw_hostsrv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
proprietary = ["mw_host/proprietary", "dep:mw_host_proprietary"]

[dependencies]
mw_host = { path = "../../lib/mw_host" }

[dependencies.mw_host_proprietary]
git = "https://github.com/IyesGames/minewars-proprietary-shim"
optional = true
